version: '3'
networks:
    static-network:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
services:
  fastapi:
    image: fastapi:v1
    volumes:
      - ./backend/:/backend/
    command: bash -c "uvicorn backend.main:app --reload --host 0.0.0.0"
    ports:
      - 8000:8000
    container_name: fastapi
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      static-network:
        ipv4_address: 172.28.1.2
  
  idom:
    image: idom:v1
    volumes:
      - ./idom_frontend/:/idom_frontend/
    command: bash -c "cd idom_frontend && python3 -m run_reload.py"
    ports:
      - 8001:8001
    container_name: idom
    networks:
      static-network:
        ipv4_address: 172.28.1.1